name: Deploy Gatsby Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.8.0'  # Utilisez Node.js 22.8.0

      - name: Install Yarn
        run: npm install -g yarn@1.22.22  # Spécifiez la version 1.22.22 de Yarn

      - name: Install dependencies
        run: yarn install

      - name: Build Gatsby site
        run: yarn build

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          eval $(ssh-agent -s)  # Démarrer l'agent SSH
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
          rsync -avz --delete public/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH
          rsync -avz emails/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH/emails
          scp handleForm.js $SERVER_USER@$SERVER_HOST:$SERVER_PATH/handleForm.js
          ssh $SERVER_USER@$SERVER_HOST << 'EOF'
            source ~/.nvm/nvm.sh
            nvm use 22.8.0
            cd $SERVER_PATH
            yarn install
            pm2 restart handleForm || pm2 start handleForm.js --name handleForm
          EOF