name: Deploy Gatsby Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Utilisez Node.js 16 ou supérieur

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build Gatsby site
        run: yarn build

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          eval $(ssh-agent -s)  # Démarrer l'agent SSH
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
          rsync -avz --delete public/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH
          rsync -avz src/static/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH/server_static