name: Deploy Gatsby Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.8.0'

      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      - name: Install dependencies
        run: yarn install

      - name: Build Gatsby site
        env:
          GATSBY_GA4_MEASUREMENT_ID: ${{ secrets.GATSBY_GA4_MEASUREMENT_ID }}
          GATSBY_RECAPTCHA_SITE_KEY: ${{ secrets.GATSBY_RECAPTCHA_SITE_KEY }}
        run: yarn build

      - name: Build Node.js server
        run: yarn build:server

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          eval $(ssh-agent -s)  # Démarrer l'agent SSH
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
          rsync -avz --exclude '.env.production' --delete public/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH
          rsync -avz --delete node_modules/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH/node_modules
          rsync -avz --delete dist/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH/dist
          scp ecosystem.config.js $SERVER_USER@$SERVER_HOST:$SERVER_PATH/ecosystem.config.js
          scp package.json $SERVER_USER@$SERVER_HOST:$SERVER_PATH/package.json

      - name: Restart PM2 server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          ssh $SERVER_USER@$SERVER_HOST "cd $SERVER_PATH && pm2 delete handleForm || true && pm2 start ecosystem.config.js --env production && pm2 save"
          